### ISSUE TITLE
demo page isn't working

### ISSUE THREAD

**Issue by bobagold** [ikr/react-star-rating-input#9]
https://ikr.su/h/react-star-rating-input/demo.html
[Error] ReferenceError: Can't find variable: Intl
	(anonymous function) (bundle.js, line 1)
	s (bundle.js, line 1)
	(anonymous function) (bundle.js, line 1)
	(anonymous function) (bundle.js, line 1)
	s (bundle.js, line 1)
	(anonymous function) (bundle.js, line 1)
	(anonymous function) (bundle.js, line 1)
	(anonymous function) (bundle.js, line 1)
	s (bundle.js, line 1)
	(anonymous function) (bundle.js, line 1)
	(anonymous function) (bundle.js, line 1)
	(anonymous function) (bundle.js, line 1)
	(anonymous function) (bundle.js, line 1)
	s (bundle.js, line 1)
	e (bundle.js, line 1)
	global code (bundle.js, line 1)

**Comment by ikr** [comment]
Fixed. Thank you!
